[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
lib_deps =1
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6.19.4
    bogde/HX711 @ ^0.7.5
    adafruit/DHT sensor library @ ^1.4.2
    adafruit/Adafruit Unified Sensor @ ^1.1.4
monitor_speed = 115200
board_build.filesystem = littlefs