[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6.21.3
    olkal/HX711_ADC @ ^1.2.9
    adafruit/DHT sensor library @ ^1.4.4
    adafruit/Adafruit Unified Sensor @ ^1.1.9
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags = -D MQTT_MAX_PACKET_SIZE=65535