[platformio]
default_envs = nodemcuv2

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_port = COM10
upload_port = COM10
monitor_speed = 115200
board_build.filesystem = littlefs


# Librerías necesarias para el proyecto
lib_deps = 
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.21.4
    olkal/HX711_ADC
    adafruit/DHT sensor library@^1.4.4
    adafruit/Adafruit Unified Sensor@^1.1.13
    NTPClient
    
build_flags = 
    -D BEARSSL_SSL_BASIC
    -D ARDUINOJSON_USE_LONG_LONG=1
