; === USB (por defecto) ===
[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
upload_port = COM11
board_build.filesystem = spiffs
lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6.19.4
    bogde/HX711 @ ^0.7.5
    adafruit/DHT sensor library @ ^1.4.2
    adafruit/Adafruit Unified Sensor @ ^1.1.4

; === OTA (Over-The-Air) ===
; Para flashear: cambiar upload_port a la IP del dispositivo
; y DEVICE_ID en config.h al ID deseado
[env:ota]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
board_build.filesystem = spiffs
lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6.19.4
    bogde/HX711 @ ^0.7.5
    adafruit/DHT sensor library @ ^1.4.2
    adafruit/Adafruit Unified Sensor @ ^1.1.4
upload_protocol = espota
upload_port = 192.168.1.92
