[env:esp32-c3-superMini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1
              -DARDUINO_USB_MODE=1

lib_deps =
    adafruit/Adafruit AHTX0 @ ^2.0.5
    adafruit/Adafruit VEML7700 Library @ ^2.1.6
    adafruit/Adafruit SSD1306 @ ^2.5.13
    adafruit/Adafruit GFX Library @ ^1.11.11
    adafruit/Adafruit BusIO @ ^1.16.2
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.3.1
